{{- if eq .Values.workloadType "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bitcoin-subtx-generator.fullname" . }}
  labels:
    {{- include "bitcoin-subtx-generator.labels" . | nindent 4 }}
spec:
  completions: {{ .Values.job.completions }}
  parallelism: {{ .Values.job.parallelism }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- with .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if eq .Values.networking.mode "multus" }}
        {{- include "bitcoin-subtx-generator.multusAnnotation" . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bitcoin-subtx-generator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "bitcoin-subtx-generator.podSpec" . | nindent 6 }}
{{- end }}
